"""Initial revision

Revision ID: fc49af2ef09b
Revises: 
Create Date: 2025-05-03 18:53:37.016542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc49af2ef09b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronmic', sa.String(), nullable=True),
    sa.Column('special', sa.String(), nullable=False),
    sa.Column('work_experience', sa.Integer(), nullable=False),
    sa.Column('adress', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('visit_card', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('booking',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('day_booking', sa.Date(), nullable=False),
    sa.Column('time_bookings', sa.Time(), nullable=False),
    sa.Column('booking_status', sa.String(), nullable=False),
    sa.Column('created_ad', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('users')
    op.drop_table('doctors')
    # ### end Alembic commands ###
